Original config.yml file:
version: 2.1
orbs:
  cypress: cypress-io/cypress@1.24.0
workflows:
  build:
    jobs:
      - cypress/run:
          start: npm start
          wait-on: 'http-get://localhost:3000'
          no-workspace: true
