version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install:
      - run:
          name: installing dev dependencies...
          command: npm ci
      - cypress/run:
          requires:
            - cypress/install
            - run
          start: 'npm start & wait-on http://localhost:3000'  # start server before running tests
