version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install:
          install: 'npm install'  # run a custom app build step
      - cypress/run:
          requires:
            - cypress/install
          start: 'npm start & wait-on http://localhost:3000'  # start server before running tests
