version: 2.1
orbs:
  cypress: cypress-io/cypress@1
  node: circleci/node@1.1.6
workflows:
  build:
    jobs:
      - cypress/install:
          build: 'npm run build'  # run a custom app build step
      - cypress/run:
          requires:
            - cypress/install
          record: true        # record results on Cypress Dashboard
      - run: 
          command: 'npm start'  # start server before running tests
          background: true
