version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - start: npm start
  Cypress:
    executor:
      name: Cypress
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - start: npx cypress open

workflows:
    build-and-test:
      jobs:
        - build-and-test
        - Cypress
          require
            - build-and-test