version: 2.1
orbs:
  cypress: cypress-io/cypress@1.23.0
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo

    steps:
      - checkout
      
      - run: npm install

      - run: npx cypress-run

      - run: npm build

